"""add work hours, accuracy snapshot, reminder uniqueness

Revision ID: 27b9e321cdce
Revises: 55c908053d18
Create Date: 2026-09-07 22:51:19.668691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b9e321cdce'
down_revision = '55c908053d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reminder_todo_type', ['todo_id', 'reminder_type'])

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accuracy_ratio', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_start_hour', sa.Integer(), server_default='9', nullable=False))
        batch_op.add_column(sa.Column('work_end_hour', sa.Integer(), server_default='17', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('work_end_hour')
        batch_op.drop_column('work_start_hour')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('accuracy_ratio')
        batch_op.drop_column('actual_minutes')

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reminder_todo_type', type_='unique')

    # ### end Alembic commands ###
