"""add scheduling fields, TimeSession, Reminder

Revision ID: 366cb7d009de
Revises: 93b7a9bccc61
Create Date: 2026-09-07 21:47:37.680218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366cb7d009de'
down_revision = '93b7a9bccc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_todo_id'), ['todo_id'], unique=False)

    op.create_table('time_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_session_todo_id'), ['todo_id'], unique=False)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('scheduled_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_todo_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_todo_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # Keep the new status column consistent with the old completed flag so
    # existing rows do not end up marked pending while completed is true.
    op.execute("UPDATE todo SET status = 'completed' WHERE completed = 1")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('timezone')
        batch_op.drop_column('email')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todo_user_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_todo_user_id'))
        batch_op.drop_column('deadline')
        batch_op.drop_column('priority')
        batch_op.drop_column('actual_end')
        batch_op.drop_column('actual_start')
        batch_op.drop_column('scheduled_end')
        batch_op.drop_column('scheduled_start')
        batch_op.drop_column('status')
        batch_op.drop_column('estimated_minutes')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('time_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_session_todo_id'))

    op.drop_table('time_session')
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_todo_id'))

    op.drop_table('reminder')
    # ### end Alembic commands ###
