"""add subtasks_json to todo

Revision ID: 55c908053d18
Revises: 366cb7d009de
Create Date: 2026-09-07 21:58:54.358028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c908053d18'
down_revision = '366cb7d009de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtasks_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('subtasks_json')

    # ### end Alembic commands ###
